### ISSUE TITLE
BitVector deserialize bug

### ISSUE THREAD

**Issue by dapplion** [ChainSafe/ssz#118]
Attempting to deserialize an altair block results in an SSZ error

```
Jun-01 13:16:57.566 [SYNC]          verbose: Batch download error id=Finalized, startEpoch=9, status=Downloading code=SSZ_SNAPPY_ERROR_DESERIALIZE_ERROR, deserializeError={"message":"Invalid deserialized bitvector length"}
Error: Invalid deserialized bitvector length
    at BitVectorType.tree_deserializeFromBytes (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/ssz/src/types/composite/bitVector.ts:124:13)
    at ContainerType.tree_deserializeFromBytes (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/ssz/src/types/composite/container.ts:369:21)
    at ContainerType.tree_deserializeFromBytes (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/ssz/src/types/composite/container.ts:369:21)
    at ContainerType.tree_deserializeFromBytes (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/ssz/src/types/composite/container.ts:369:21)
    at ContainerType.tree_deserializeFromBytes (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/ssz/src/types/composite/container.ts:369:21)
    at ContainerType.tree_deserialize (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/ssz/src/types/composite/abstract.ts:119:17)
    at ContainerType.createTreeBackedFromBytes (/home/lion/Code/eth2.0/lodestar/node_modules/@chainsafe/ssz/src/types/composite/abstract.ts:396:39)
    at deserializeSszBody (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/network/reqresp/encodingStrategies/sszSnappy/decode.ts:139:24)
    at readSszSnappyPayload (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/network/reqresp/encodingStrategies/sszSnappy/decode.ts:34:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: SSZ_SNAPPY_ERROR_DESERIALIZE_ERROR
    at deserializeSszBody (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/network/reqresp/encodingStrategies/sszSnappy/decode.ts:144:11)
    at readSszSnappyPayload (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/network/reqresp/encodingStrategies/sszSnappy/decode.ts:34:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at readEncodedPayload (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/network/reqresp/encodingStrategies/index.ts:25:14)
    at chunk (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/network/reqresp/encoders/responseDecode.ts:62:13)
    at /home/lion/Code/eth2.0/lodestar/packages/lodestar/src/network/reqresp/utils/onChunk.ts:7:22
    at response (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/network/reqresp/request/responseTimeoutsHandler.ts:39:7)
    at /home/lion/Code/eth2.0/lodestar/packages/lodestar/src/network/reqresp/request/collectResponses.ts:25:22
    at withTimeout (/home/lion/Code/eth2.0/lodestar/packages/utils/src/timeout.ts:20:12)
    at sendRequest (/home/lion/Code/eth2.0/lodestar/packages/lodestar/src/network/reqresp/request/index.ts:139:25)
```

Config: https://github.com/eth2-clients/eth2-networks/pull/47

Block:

```
0x640000008539e6c27cbca13373395583fb3b2b324669db949582cbcd4abf7bd81c2b289690c564799b74884ec99d8c501d690fea05df41a8a93bff241208bf03a94e15e4a56ba35d6d669ba188dfcfec267f4c4dd11235f81f20510da8cf23b1e37f810841010000000000001f02000000000000b422275e97f488979b7f85735370952ea3b88fba39175a689e54a2d4b379d4b16f0761935eae7d354c215549e06ee14d3b98f4eff470cc470e8b563bfafbb91654000000ad9ac936202876254219fae2b6bffa96968c21360040413ae4a6197c9b83fe0c3d77f136eb10127b415d59f7e6ec622d186d8b76fbd502badb80cac59eb2315f2b137eb2095b097857a95a229b532911e7c9d75d83ff98859d01fcfb53927149d70a234731285c6804c2a4f56711ddb8c82c99740f207854891028af34e27e5e00000000000000006342bde06c37c72e50401c7c6ca3a898c129da44cb647c1de60584c3b3414faa74656b752f7632312e352e302b35342d673633376631316400000000000000007c0100007c0100007c0100006e0200006e02000017ccd8d26fd7b9375fbdd6cf69b7370857bfa5c78d4937d53f181132b448268432f34248cbb7f54e3730278014170f9e27af2ba3ecbcadf5017e6161abe9a7b980c0117e338f5db745d1ff4233e313a9f9f04b20bee6f80cd68ef5fce77e3ac9888913438274bd7be6c1739744bc84ea15c4058b5825b1008e9e65f899b17e49ca60e224a3ca211ad8410364aeb71d00396b397d2fb8eaae6e3bfca18fb7f31704000000e400000040010000000000000000000000000000b422275e97f488979b7f85735370952ea3b88fba39175a689e54a2d4b379d4b108000000000000008da011351e515f87967e99e9b7f0a6c0e48cade59826c065969a055b290af9dc0a00000000000000b422275e97f488979b7f85735370952ea3b88fba39175a689e54a2d4b379d4b1b9f8367e9ea68a5db480abf345785ed5b240d81053ef2d0e2bcaa3339a2bac52ed0c66059f9eb93199e8f1a646ea063f1723a6076d361992ac14578f0f83da63f9d30af9259ec5eaf40c84f96f38ed79a3e014663603b565afc5f4fbf6d940a2ffffffffffffffffff0f
```

**Comment by dapplion** [comment]
Fixed with https://github.com/ChainSafe/ssz/pull/116
